// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PZJDobC4t3QrqBp79cac3Bs5VJ6QxQ4',
    appId: '1:464102189135:android:f2abf02198680e7f04e23a',
    messagingSenderId: '464102189135',
    projectId: 'medirem-937e0',
    storageBucket: 'medirem-937e0.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi-M9_cLaprLTT4LMjdKuoTu9olgdAQ0s',
    appId: '1:464102189135:web:7f9342ef04c4588d04e23a',
    messagingSenderId: '464102189135',
    projectId: 'medirem-937e0',
    authDomain: 'medirem-937e0.firebaseapp.com',
    storageBucket: 'medirem-937e0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGjfBqrKQtHUYTbYRfRBLtOVqWWgbSls',
    appId: '1:464102189135:ios:384b4b70ea12115404e23a',
    messagingSenderId: '464102189135',
    projectId: 'medirem-937e0',
    storageBucket: 'medirem-937e0.firebasestorage.app',
    iosBundleId: 'com.example.medReminder',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGjfBqrKQtHUYTbYRfRBLtOVqWWgbSls',
    appId: '1:464102189135:ios:384b4b70ea12115404e23a',
    messagingSenderId: '464102189135',
    projectId: 'medirem-937e0',
    storageBucket: 'medirem-937e0.firebasestorage.app',
    iosBundleId: 'com.example.medReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi-M9_cLaprLTT4LMjdKuoTu9olgdAQ0s',
    appId: '1:464102189135:web:c57af2f11e34e2f204e23a',
    messagingSenderId: '464102189135',
    projectId: 'medirem-937e0',
    authDomain: 'medirem-937e0.firebaseapp.com',
    storageBucket: 'medirem-937e0.firebasestorage.app',
  );

}